//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NZazuFiddle.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ShellView : global::System.Configuration.ApplicationSettingsBase {
        
        private static ShellView defaultInstance = ((ShellView)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ShellView())));
        
        public static ShellView Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double LeftSplitter {
            get {
                return ((double)(this["LeftSplitter"]));
            }
            set {
                this["LeftSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double MidSplitter {
            get {
                return ((double)(this["MidSplitter"]));
            }
            set {
                this["MidSplitter"] = value;
            }
        }
    }
}
